#!/bin/bash

docker kill dev-web 2>&1

docker run --rm -d --name dev-web -v $PWD/web_front:/data/web_front -v $PWD/shared_components:/data/shared_components -p 8080:8080 dev-nodejs bash -c "cd /data/web_front; npm install; npm run dev"
