version: '3'
services:
  web:
    image: dev-nodejs:latest
    ports:
      - "${WEB_LOCAL_PORT}:${WEB_PORT}"
    volumes:
      - ./web_front:/data/web_front
      - ./shared_components:/data/shared_components
    command: ${WEB_CMD}
    environment:
      PORT: "${WEB_PORT}"
      SERVER_URL: ${WEB_TO_SERVER_URL}
  socket-server:
    image: dev-nodejs:latest
    ports:
      - "${SERVER_LOCAL_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/data/server
      - ./shared_components:/data/shared_components
    command: ${SERVER_CMD}
    depends_on:
      - db
    links:
      - "db:database"
    environment:
      PORT: ${SERVER_PORT}
      DB_URL: ${SERVER_TO_DB_URL}
      NODE_ENV: ${ENV_TYPE}
  db:
    image: postgres:9
    restart: always
    ports:
      - "${DB_LOCAL_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
      